# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:9-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    parallelism: 4

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Fetch dependencies
          command: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Compile code
          command: gradle compileJava

      - run:
          name: Create distribution
          command: |
              gradle distTar
              mv build/distributions/bluestone*.tar /tmp/bluestone.tar

      - store_artifacts:
          path: /tmp/bluestone.tar
          destination: bluestone.tar

      - run:
          name: Create shadow JAR
          command: |
              gradle shadowJar
              mv build/libs/bluestone*-all.jar /tmp/bluestone.jar

      - store_artifacts:
          path: /tmp/bluestone.jar
          destination: bluestone.jar
